
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvkdbrqxbshlidxxhovq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2a2RicnF4YnNobGlkeHhob3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjM0NzAsImV4cCI6MjA1ODMzOTQ3MH0.xu3CLvZcou9v6h8a9JGqXvbVKOaYu1HS1OkUExKOAgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});

// Export a function to validate the current session token
export const validateSession = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error("Session validation failed:", error);
      return false;
    }
    
    if (!data.session) {
      console.log("No active session found");
      return false;
    }
    
    return true;
  } catch (e) {
    console.error("Exception during session validation:", e);
    return false;
  }
};
